### ISSUE TITLE
Some missing images

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armorlab_web#1]
There appears to be some missing images at the [ArmorLab Manual](https://armorlab.org/manual). They appear to never having been uploaded initially.

![image](https://user-images.githubusercontent.com/69180012/189554449-955566fc-eaf1-4b4c-9427-74faae805cd2.png)

**Comment by luboslenco** [comment]
Thanks for notice, will put it all in order once https://armorlab.org/download is live, right now the embedded videos are also placeholders from armorpaint.
